development: &development
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: sandbox_development
  host: localhost
  pool: 5
  username: srirangarajan
 
test: &test
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: sandbox_test
  host: localhost
  pool: 5
  username: srirangarajan
